### ISSUE TITLE
libykneomgr requires pcscd

### ISSUE THREAD

**Issue by dainnilsson** [Yubico/libykneomgr-dpkg#1]
The ykneomgr tool seems to require pcscd to work. This should be a dependency. See Yubico/yubikey-neo-manager-dpkg#2

**Comment by klali** [comment]
the tool has a dependency on pcscd, I'm thinking the lib should have a recommends instead.
@jas4711 @dainnilsson ?

**Comment by jas4711** [comment]
I don't think there is a strong policy on the exact method to achieve the proper dependency here (tool vs lib, depends vs suggests vs recommends) -- and a recommends: pcscd for libykneomgr0 would be fine to me.

**Comment by artem-sidorenko** [comment]
In the initial issue (https://github.com/Yubico/yubikey-neo-manager-dpkg/issues/2) my problem was the missing dependency but a recommendation. Now we have exact the same picture like before, one issue refers to another one, and the second one is closed as "resolved", somehow funny:)

IMHO, if something is needed to provide the desired functionality its a dependency and not a recommendation (which is optional).

is pcscd required for this library or tool to provide the functionality and work?

I'm not an expert in this area, but for me it was the only one solution to get ykneomgr working (after several hours of troubleshooting, as usually I don't check all recommendations from all possible packages because of reasons above)

**Comment by dainnilsson** [comment]
How are you installing? Don't packages in "Recommends" get pulled in automatically by default?

**Comment by artem-sidorenko** [comment]
I use Mint/Ubuntu with apt-get,

If you check the part of [debian manual](https://www.debian.org/doc/debian-policy/ch-relationships.html#s-binarydeps) about dependencies you will find following:

```
Depends
This declares an absolute dependency. A package will not be configured unless all of the packages listed in its Depends field have been correctly configured (unless there is a circular dependency as described above).

The Depends field should be used if the depended-on package is required for the depending package to provide a significant amount of functionality. 
...
Recommends

This declares a strong, but not absolute, dependency.

The Recommends field should list packages that would be found together with this one in all but unusual installations.
...
```

So, Depends must be used for deps which are required to provide the functionality, Recommends results to "might be installed together"|"not"|"not usually"

If pcscd is required to do the job IMHO it should be in "Depends" and not "Recommends", but I don't know if pcscd is the only one way here or the library supports some other things like opensc

**Comment by klali** [comment]
Hello,

I think the key part from the manual is "The Recommends field should list packages that would be found together with this one in all but unusual installations."
The reason we went with Recommends is that pcscd isn't strictly needed for the binaries to run or for building packages depending on these. Unless you use apt-get with --no-install-recommends recommended packages should be installed just as dependencies, do you have a use-case where this is not true?

/klas

**Comment by artem-sidorenko** [comment]
If I take a look to my default apt configuration, I see following:

``` bash
$ cat /etc/apt/apt.conf.d/00recommends 
APT::Install-Recommends "false";
Aptitude::Recommends-Important "false";
```

I don't know if this is a Mint or Ubuntu default (Mint is built on top of Ubuntu), but I have it on all my Mint installations

**Comment by klali** [comment]
Yeah.. this seams to be a "feature" of mint: https://bugs.launchpad.net/linuxmint/+bug/1266234 there seems to be quite a bit of people with problems due to this and packages being unsupported on mint.

The Yubico packages are built for (and supported) on debian and ubuntu.
